# Generated by Django 5.1.1 on 2024-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("publish_date", models.DateField()),
                ("category", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "book",
                "managed": False,
            },
        ),
    ]
